# Generated by Django 6.1 on 2026-08-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_empleado_horariosemanal'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('dias_laborados', models.IntegerField(default=15)),
                ('sueldo_devengado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_recibir', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada_real', models.TimeField()),
                ('hora_salida_real', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
    ]
