# Generated by Django 6.1 on 2026-08-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True, verbose_name='ID Empleado')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='C.C.')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('tipo_rol', models.CharField(max_length=50, verbose_name='Tipo de Rol')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Básico')),
                ('grupo_descanso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo de Descanso')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(choices=[('Semana 1', 'Semana 1'), ('Semana 2', 'Semana 2')], max_length=20)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('es_descanso', models.BooleanField(default=False)),
            ],
        ),
    ]
