# Generated by Django 6.1 on 2026-08-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_empleado_horariosemanal'),
        ('nomina', '0002_facturanomina_marcacion_delete_nomina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.AddField(
            model_name='horariosemanal',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='colaboradores.empleado'),
        ),
    ]
