# Generated by Django 6.1 on 2026-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_delete_colaborador_horariosemanal_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='grupo_descanso',
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_entrada_teorica',
            field=models.TimeField(default='02:00:00'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_salida_teorica',
            field=models.TimeField(default='11:00:00'),
        ),
    ]
