# Generated by Django 6.1 on 2026-08-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_remove_empleado_grupo_descanso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='hora_entrada_teorica',
            field=models.TimeField(default='02:00:00', verbose_name='Entrada Teórica'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hora_salida_teorica',
            field=models.TimeField(default='11:00:00', verbose_name='Salida Teórica'),
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dia', models.CharField(max_length=20, verbose_name='Día')),
                ('entrada_teorica', models.TimeField(verbose_name='Entrada Teórica')),
                ('salida_teorica', models.TimeField(verbose_name='Salida Teórica')),
                ('entrada_real', models.TimeField(blank=True, null=True, verbose_name='Entrada Real')),
                ('salida_real', models.TimeField(blank=True, null=True, verbose_name='Salida Real')),
                ('novedad', models.CharField(default='Normal', max_length=50, verbose_name='Novedad / Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='colaboradores.empleado')),
            ],
        ),
    ]
